# Generated by Django 4.0.6 on 2022-11-15 16:43

import TSApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsteacher',
            name='name',
        ),
        migrations.AddField(
            model_name='tsteacher',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[TSApp.models.validate_capitalized]),
        ),
    ]
