# Generated by Django 4.0.6 on 2022-11-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0002_remove_tsteacher_name_tsteacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsteacher',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
