# Generated by Django 4.0.6 on 2022-11-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0004_task_ctask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctask',
            name='attachment',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
