# Generated by Django 4.0.6 on 2022-11-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0005_ctask_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctask',
            name='e_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ctask',
            name='s_date',
            field=models.TextField(),
        ),
    ]
