# Generated by Django 4.0.6 on 2022-11-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0006_alter_ctask_e_date_alter_ctask_s_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctask',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TSApp.tsstudent'),
            preserve_default=False,
        ),
    ]
