# Generated by Django 4.0.6 on 2022-11-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0007_alter_ctask_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctask',
            old_name='task',
            new_name='taske',
        ),
        migrations.AlterField(
            model_name='ctask',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSApp.task'),
        ),
    ]
