# Generated by Django 4.0.6 on 2022-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSApp', '0009_rename_task_task_taske'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctask',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
